languageCode = "zh-Hant"
languageName = "繁體中文 (香港)"
languageDirection = "ltr"
weight = 1
title = "Himphen's Blog"
copyright = "© 2025 Himphen."

[params]
  dateFormat = "2006年01月02日"
  description = "Himphen 的個人部落格 - 分享技術、生活和想法"
  
  [params.author]
    name = "Himphen"
    image = "avatar.jpg"
    bio = ""
    headline = ""
    
    [[params.author.links]]
      name = "GitHub"
      url = "https://github.com/himphen"
      icon = "github"
      weight = 10 