languageCode = "zh-Hant"
languageName = "繁體中文 (香港)"
languageDirection = "ltr"
weight = 1
title = "Himphen's Digital Garden"
copyright = "© 2025 Himphen."

[params]
  dateFormat = "2006年01月02日"
  description = "A personal digital garden sharing thoughts, experiences, and insights on technology, travel, and life in Australia."
  
  [params.author]
    name = "Himphen"
    image = "avatar.jpg"
    bio = ""
    headline = ""
    
    [[params.author.links]]
      name = "GitHub"
      url = "https://github.com/himphen"
      icon = "github"
      weight = 10 